### ISSUE TITLE
Access downloaded files / specify the path of the downloaded file

### ISSUE THREAD

**Issue by kiralyta** [AlwaysLoveme/capacitor-plugin-filedownload#2]
So the package works fine, but it downloads my file (without being able to select the path) to */storage/emulated/0/Android/data/{appId}/files/{fileName}*

How can I open this file instantly, or how can I make the plugin download the files to the Download folder of the device?

I'm trying to use the package to download .apk files (app updates) and install them.

**Comment by AlwaysLoveme** [comment]
> 

use this plugin to open file:
https://github.com/capacitor-community/file-opener

**Comment by AlwaysLoveme** [comment]
> So the package works fine, but it downloads my file (without being able to select the path) to _/storage/emulated/0/Android/data/{appId}/files/{fileName}_
> 
> How can I open this file instantly, or how can I make the plugin download the files to the Download folder of the device?
> 
> I'm trying to use the package to download .apk files (app updates) and install them.

use this plugin to open file:
https://github.com/capacitor-community/file-opener
