### ISSUE TITLE
' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by sksk008** [AlwaysLoveme/capacitor-plugin-filedownload#3]
how to pass header with request ?

**Comment by AlwaysLoveme** [comment]
> how to pass header with request ?


Cross-domain problems need to be solved by the backend, which is more reasonable

**Comment by AlwaysLoveme** [comment]
> how to pass header with request ?

It's supported in the latest version
