### ISSUE TITLE
English  language not showing at downloading time.

### ISSUE THREAD

**Issue by sksk008** [AlwaysLoveme/capacitor-plugin-filedownload#4]
![Screenshot_2023-02-16-18-13-47-184_io ionic starter](https://user-images.githubusercontent.com/36026393/219368357-7b05f743-53b5-4f4a-bbb0-2b84ac704440.jpg)

how to display message in English language.

**Comment by AlwaysLoveme** [comment]
> ![Screenshot_2023-02-16-18-13-47-184_io ionic starter](https://user-images.githubusercontent.com/36026393/219368357-7b05f743-53b5-4f4a-bbb0-2b84ac704440.jpg)
> 
> how to display message in English language.


I will provide property configuration in the next version

**Comment by jodusan** [comment]
Is there an option to choose language?

**Comment by AlwaysLoveme** [comment]
> Is there an option to choose language?

The relevant configuration is provided in the latest version，Please update to the latest version，thks

**Comment by jodusan** [comment]
Great! Thank you! Feel free to close this issue!
