### ISSUE TITLE
Is it possible to change destination folder?

### ISSUE THREAD

**Issue by jodusan** [AlwaysLoveme/capacitor-plugin-filedownload#5]
I am trying to download a file to a folder, but it always sets it in files folder when using ExternalStorage on android, is it possible to store it in a subfolder?

**Comment by technophilix** [comment]
path = "22A433FD-D82D-4989-8BE6-9FC49DEA20BB/"+makeid(8);
      const fdres = await FileDownload.download({
        uri: file,
        fileName: path,
      });

**Comment by Tragio** [comment]
@AlwaysLoveme thank you for your amazing work. I'm also with the same question. Because on iOS it seems to default to Documents and on Android to External Storage 🤔

**Comment by AlwaysLoveme** [comment]
> @AlwaysLoveme thank you for your amazing work. I'm also with the same question. Because on iOS it seems to default to Documents and on Android to External Storage 🤔

thank you for using, I will provide property configuration in the next version

**Comment by Tragio** [comment]
@AlwaysLoveme awesome, in that way, I'll postpone the release of the Android App. Do you have any ETA for it? 🤩

**Comment by AlwaysLoveme** [comment]
> @AlwaysLoveme awesome, in that way, I'll postpone the release of the Android App. Do you have any ETA for it? 🤩 

it's supported in the latest version

**Comment by Tragio** [comment]
@AlwaysLoveme thank you for your amazing work. Seems that you mistyped the `Documents` location.

![CleanShot 2023-05-28 at 09 26 29](https://github.com/AlwaysLoveme/capacitor-plugin-filedownload/assets/5109593/a4aae4a0-3992-4251-a02b-1f6948eddb72)

**Comment by AlwaysLoveme** [comment]
> @AlwaysLoveme thank you for your amazing work. Seems that you mistyped the `Documents` location.
> 
> ![CleanShot 2023-05-28 at 09 26 29](https://user-images.githubusercontent.com/5109593/241527580-a4aae4a0-3992-4251-a02b-1f6948eddb72.jpg)

Thanks for pointing out the bug, it has been fixed in the latest version@1.0.8
