### ISSUE TITLE
下载文件需要请求头参数和请求参数

### ISSUE THREAD

**Issue by Ryanccl** [AlwaysLoveme/capacitor-plugin-filedownload#6]
headers: {
        Authorization: token,
      },
      params: {
        params: 'params1',
      },

**Comment by AlwaysLoveme** [comment]
>  headers: {
> 
>         Authorization: token,
> 
>       },
> 
>       params: {
> 
>         params: 'params1',
> 
>       },

你好，近期内有空会加上，如果你能提个 pr 那就再好不过啦

**Comment by AlwaysLoveme** [comment]
>  headers: {
> 
>         Authorization: token,
> 
>       },
> 
>       params: {
> 
>         params: 'params1',
> 
>       },

最新版本已加上
