### ISSUE TITLE
capacitor 5

### ISSUE THREAD

**Issue by luk156** [AlwaysLoveme/capacitor-plugin-filedownload#7]
Could not resolve dependency:
npm ERR! peer @capacitor/core@"^4.0.0" from capacitor-plugin-filedownload@1.0.5

**Comment by AlwaysLoveme** [comment]
> Could not resolve dependency:
> 
> npm ERR! peer @capacitor/core@"^4.0.0" from capacitor-plugin-filedownload@1.0.5
> 
> 

Will support v5 in a few days

**Comment by Tragio** [comment]
Did you try version 5? From my side, all is working 🤔

**Comment by AlwaysLoveme** [comment]
> Did you try version 5? From my side, all is working 🤔

I didn't do the adaptation for v5 and didn't try v5😂

**Comment by Serroda** [comment]
> Did you try version 5? From my side, all is working 🤔

Doesn't work for me
