### ISSUE TITLE
notifyListeners "downloadProgress" not implemented for android? 

### ISSUE THREAD

**Issue by ariane10** [AlwaysLoveme/capacitor-plugin-filedownload#8]
I want to notify the user the percentage of the download that has been completed, but I cannot access the process data in the listener. 

const eventListener = await FileDownload.addListener('downloadProgress', data =>{
  console.log(data.progress);
})

**Comment by AlwaysLoveme** [comment]
> I want to notify the user the percentage of the download that has been completed, but I cannot access the process data in the listener. 
> 
> 
> 
> const eventListener = await FileDownload.addListener('downloadProgress', data =>{
> 
>   console.log(data.progress);
> 
> })

Fixed in latest version
